### ISSUE TITLE
MSMARCO v2 - updated qrels

### ISSUE THREAD

**Issue by sebastian-hofstaetter** [allenai/ir_datasets#104]
**Describe the bug**
This commit (https://github.com/microsoft/msmarco/commit/41b3a684ed8ebd4e753250c3687547a77c62e7dd) updated the qrel files & changed the md5 hashes, now the download of the qrels raises a HashVerificationError

**Affected dataset(s)**

msmarco-passage-v2

**To Reproduce**
Try to iterate over msmarco-passage-v2 qrels (dev1,dev2 and train affected) -> get error

**Expected behavior**

Matching md5 hashes

**Additional context**
Full traceback:

```
[INFO] If you have a local copy of https://msmarco.blob.core.windows.net/msmarcoranking/passv2_dev_qrels.tsv, you can symlink it here to avoid downloading it again: /newstorage4/hofstaetter/downloads/e3610e344dac10adee03db1882916adf
[INFO] [starting] https://msmarco.blob.core.windows.net/msmarcoranking/passv2_dev_qrels.tsv
[INFO] [finished] https://msmarco.blob.core.windows.net/msmarcoranking/passv2_dev_qrels.tsv: [00:00] [165kB] [332kB/s]
[WARNING] Download failed: Expected md5 hash to be e3610e344dac10adee03db1882916adf but got 10f9263260d206d8fb8f13864aea123a
Traceback (most recent call last):
  File "preprocessing/ir_datasets/get_for_dense_retrieval.py", line 60, in <module>
    for qrel in dataset.qrels_iter():
  File "/mnt/nvme-local/hofstaetter/conda/dl/lib/python3.8/site-packages/ir_datasets/formats/trec.py", line 355, in qrels_iter
    with self._qrels_dlc.stream() as f:
  File "/mnt/nvme-local/hofstaetter/conda/dl/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/mnt/nvme-local/hofstaetter/conda/dl/lib/python3.8/site-packages/ir_datasets/util/download.py", line 249, in stream
    with open(self.path(), 'rb') as f:
  File "/mnt/nvme-local/hofstaetter/conda/dl/lib/python3.8/site-packages/ir_datasets/util/download.py", line 236, in path
    raise errors[1][1]
  File "/mnt/nvme-local/hofstaetter/conda/dl/lib/python3.8/site-packages/ir_datasets/util/download.py", line 226, in path
    shutil.copyfileobj(stream, f)
  File "/mnt/nvme-local/hofstaetter/conda/dl/lib/python3.8/shutil.py", line 205, in copyfileobj
    buf = fsrc_read(length)
  File "/mnt/nvme-local/hofstaetter/conda/dl/lib/python3.8/site-packages/ir_datasets/util/hash.py", line 51, in readinto
    self._verifier.__exit__(None, None, None)
  File "/mnt/nvme-local/hofstaetter/conda/dl/lib/python3.8/site-packages/ir_datasets/util/hash.py", line 32, in __exit__
    raise HashVerificationError(f"Expected {self.algo} hash to be {self.expected} but got {h}")
ir_datasets.util.hash.HashVerificationError: Expected md5 hash to be e3610e344dac10adee03db1882916adf but got 10f9263260d206d8fb8f13864aea123a
```

Thanks,
Sebastian

**Comment by seanmacavaney** [comment]
This has [already been fixed](https://github.com/allenai/ir_datasets/commit/4bf53f1794526f24d58356846f3c8e12b374aa99); a new version just hasn't been pushed to pypi yet. If you install from the repository, you should be good:

```
pip install --upgrade git+https://github.com/allenai/ir_datasets.git
```

**Comment by sebastian-hofstaetter** [comment]
Awesome thanks for the quick response; sorry I didn't see the fix.
Best,
Sebastian

**Comment by seanmacavaney** [comment]
No worries!
