### ISSUE TITLE
os.mkdir() fails if the target exists as a symlink

### ISSUE THREAD

**Issue by cmacdonald** [allenai/ir_datasets#107]
**Describe the bug**

os.mkdir() fails if the target exists as a symlink

```
Traceback (most recent call last):
...
    from .datasets import Dataset
  File "/users/tr.craigm/anaconda3/envs/trec2021/lib/python3.7/site-packages/pyterrier/datasets.py", line 995, in <module>
    import ir_datasets
  File "/users/tr.craigm/anaconda3/envs/trec2021/lib/python3.7/site-packages/ir_datasets/__init__.py", line 6, in <module>
    from . import datasets
  File "/users/tr.craigm/anaconda3/envs/trec2021/lib/python3.7/site-packages/ir_datasets/datasets/__init__.py", line 2, in <module>
    from . import antique
  File "/users/tr.craigm/anaconda3/envs/trec2021/lib/python3.7/site-packages/ir_datasets/datasets/antique.py", line 75, in <module>
    collection, subsets = _init()
  File "/users/tr.craigm/anaconda3/envs/trec2021/lib/python3.7/site-packages/ir_datasets/datasets/antique.py", line 34, in _init
    base_path = ir_datasets.util.home_path() / NAME
  File "/users/tr.craigm/anaconda3/envs/trec2021/lib/python3.7/site-packages/ir_datasets/util/__init__.py", line 26, in home_path
    p.mkdir(parents=True, exist_ok=True)
  File "/users/tr.craigm/anaconda3/envs/trec2021/lib/python3.7/pathlib.py", line 1273, in mkdir
    self._accessor.mkdir(self, mode)
FileExistsError: [Errno 17] File exists: '/users/craigm/.ir_datasets'
```

**To Reproduce**
$ls -l /users/craigm/.ir_datasets
lrwxrwxrwx 1 craigm csstaff 46 Jul  4 00:34 /users/craigm/.ir_datasets -> /bla/craigm/dot.ir_datasets/

**Expected behavior**

Check it exists before creating it
https://stackoverflow.com/a/18973480

**Comment by seanmacavaney** [comment]
That's strange- that's what `exist_ok=True` is supposed to take care of. Based on other answers from the link above, it raises the error of the path is not a directory.

I normally use irds with a linked data directory as well and it hasn't caused problems for me. I'm able to reproduce the problem when the target of the link doesn't exist and consequently wouldn't be able to be used, e.g., `/home/sean/.ir_datasets -> foo`. In the above example, is `/bla/craigm/dot.ir_datasets/` available/mounted/etc?

Maybe the solution here is to instead wrap it in a try-catch and provide a more helpful message?

**Comment by cmacdonald** [comment]
it could have been an NFS timeout due to heavy traffic. Worked fine once if put if not os.path.exists() before it.

**Comment by seanmacavaney** [comment]
Huh, okay. There are a bunch of places that do mkdir operations throughout the codebase. Maybe it'd be best to have a shared util that does this? Or maybe since `home_path` is (almost?) always be called before all other subpaths, triggering NSF to load via os.path.exists just once at the root is sufficient?

**Comment by seanmacavaney** [comment]
Going with the latter option -- only checking for irds home/tmp base directories. We'll see if this is sufficient or if the problem pops up again. If so, the former solution may be needed.
